[package]
name = "bsoky-common-cpu"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
bsoky-common-cgpu = { path = "../bsoky-common-cgpu" }
rand = "0.8.4"
rand_pcg = "0.3.1"
packed_struct = "0.10.0"
noise = "0.7"
