[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
common-no-std = { path="../common-no-std" }
dot_vox = { version="4.1.0", optional = true }

[features]
default = ["svo-vox"]
svo-vox = ["dot_vox"]
