[package]
name = "bsoky-no-std"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path="../common" }

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
glam = { version = "0.20", features = ["bytemuck"] }
bevy_crevice = { version = "0.6.0", features=["glam" ] }